### PR TITLE
Upgrade to null safety

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
@jakemac53 for something like that, which is just a bunch of constants, does it make sense to go directly to a stable, minor release?

**Comment by jakemac53** [comment]
I can't imagine how we would break a package like this during beta, nor how the migration could be breaking given there are no methods, so it seems reasonable to me.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by mit-mit** [comment]
@gspencergoog can you please publish?

**Comment by gspencergoog** [comment]
Sure, will do.

**Comment by gspencergoog** [comment]
Published 1.1.0

**Pull request merged**
